name: .NET Core

on:
  push:
    branches: [ master ]
    paths: 
      - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'apis/poi/**'

defaults:
  run:
    working-directory: 'apis/poi/'

jobs:
  test:
    defaults:
       run:
        working-directory: apis/poi
    name: POI API Unit Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: apis/poi/tests/UnitTests
  build:
    name: poi api docker build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    #needs: test ##used for action development
    steps:
      - uses: actions/checkout@v2
      - name: docker build and push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: devopsoh/api-poi
          registry: openhackq811qdi1acr.azurecr.io
          dockerfile: apis/poi/web/Dockerfile
          path: apis/poi/web
          tag_with_ref: true
          tag_with_sha: true
  deploy:
    name: POI API Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Get short SHA
        run: echo "::set-env name=short_sha::$(git rev-parse --short=7 HEAD)"
      - name: "Login via Azure CLI"
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "openhackq811qdi1poi"
          images: "openhackq811qdi1acr.azurecr.io/devopsoh/api-poi:sha-${{ env.short_sha }}"
          slot-name: production 
