# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths: 
      - 'apis/user-java/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'apis/user-java/**'

defaults:
  run:
    working-directory: apis/user-java

jobs:
  test:
    name: user-java unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean install
        mvn test

  build:
    name: user-java docker build
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - name: docker build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: devopsoh/api-user-java
        registry: openhackq811qdi1acr.azurecr.io
        tag_with_ref: true
        tag_with_sha: true
