# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build validation

on:
  push:
    branches: 
    - master
    paths:
    - 'apis/userprofile/**'

  pull_request:
    branches: 
    - 'master'
    paths: 
    - 'apis/userprofile/**'

jobs:
  test:
    defaults:
      run:
        working-directory: apis/userprofile

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    name: userprofile unit tests
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm CI, Build and Test
      run: |
        npm ci
        npm run build --if-present
        npm test
  
  build:
    name: userprofile docker build & push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: docker build and push
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: devopsoh/api-userprofile
        registry: openhackq811qdi1acr.azurecr.io
        dockerfile: apis/userprofile/Dockerfile
        path: apis/userprofile
        tags: ${{ github.run_number }}
  
  deploy:
    name: userprofile deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "openhackq811qdi1userprofile"
          images: "openhackq811qdi1acr.azurecr.io/devopsoh/api-userprofile:${{ github.run_number }}"
          slot-name: production
        
